### PR TITLE
Rename nav.js to Nav.js

### PR DESCRIPTION
**Pull request by LucasFrecia**
Renaming file to avoid following error when running webpack:

ERROR in ./src/js/pages/Layout.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/layout/Nav in /var/www/html/react-js-tutorials/2-react-router/src/js/pages
 @ ./src/js/pages/Layout.js 20:11-46

### CODE REVIEW

**Comment by KSMorozov** [comment]
**22 days ago...
no idea why its not merged yet.**

**Comment by Sudakatux** [comment]
Seems to solve a simple mistake. Please merge

**Comment by willrstern** [comment]
Ah!  Fell into the email black hole!   Merging.

**Comment by KSMorozov** [comment]
@willrstern thanks :)

**Pull request merged**
